# Generated by Django 5.2.8 on 2025-11-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Canceled'), ('past_due', 'Past Due'), ('trialing', 'Trialing')], default='trialing', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='studentprofile',
            name='unique_profile_student_per_school',
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['school', 'lesson_type'], name='DriveApp_le_school__4d66d3_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['school', 'status'], name='DriveApp_st_school__563859_idx'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='DriveApp.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='schoolsubscription',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='DriveApp.drivingschool'),
        ),
    ]
