# Generated by Django 5.2.8 on 2025-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0002_schoolsubscription_alter_lesson_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentperformanceprediction',
            name='confidence_level',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformanceprediction',
            name='predicted_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentperformanceprediction',
            name='recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentperformanceprediction',
            name='risk_factors',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='studentperformanceprediction',
            name='success_probability',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
