# Generated by Django 5.2.8 on 2025-11-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0003_alter_studentperformanceprediction_confidence_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_feedback', to='DriveApp.lesson'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_feedback', to='DriveApp.studentprofile'),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='DriveApp.subscriptionplan'),
        ),
    ]
