# Generated by Django 5.2.8 on 2025-12-04 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0004_alter_feedback_lesson_alter_feedback_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='total_hours_driving',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='total_hours_theory',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
