# Generated by Django 5.2.8 on 2025-12-12 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0005_alter_studentprofile_total_hours_driving_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiclePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='DriveApp.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle Picture',
                'verbose_name_plural': 'Vehicle Pictures',
                'ordering': ['-is_primary', '-uploaded_at'],
                'indexes': [models.Index(fields=['vehicle', 'is_primary'], name='DriveApp_ve_vehicle_69395f_idx'), models.Index(fields=['uploaded_at'], name='DriveApp_ve_uploade_8370b3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('vehicle', 'is_primary'), name='unique_primary_picture_per_vehicle')],
            },
        ),
    ]
