# Generated by Django 5.2.8 on 2025-12-12 15:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0006_vehiclepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepicture',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='vehicle_image'),
        ),
    ]
