# Generated by Django 5.2.8 on 2025-12-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0007_vehiclepicture_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vehiclepicture',
            name='unique_primary_picture_per_vehicle',
        ),
    ]
