# Generated by Django 5.2.8 on 2026-01-05 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0008_remove_vehiclepicture_unique_primary_picture_per_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('S', 'Scheduled'), ('C', 'Completed'), ('P', 'Paused'), ('X', 'Cancelled')], db_index=True, default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='schoolsubscription',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='DriveApp.drivingschool'),
        ),
    ]
