# Generated by Django 5.2.8 on 2026-01-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0009_alter_lesson_status_alter_schoolsubscription_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('A', 'Admin'), ('S', 'Student'), ('I', 'Instructor')], max_length=1, null=True),
        ),
    ]
