# Generated by Django 5.2.8 on 2026-06-01 21:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DriveApp', '0012_alter_studentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_students',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_license_type',
            field=models.CharField(choices=[('C', 'Car'), ('M', 'Moto'), ('A', 'All')], default='A', max_length=1),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='DriveApp.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='DriveApp.studentprofile')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['student', 'lesson'], name='DriveApp_en_student_0cc56e_idx')],
                'constraints': [models.UniqueConstraint(fields=('student', 'lesson'), name='unique_student_lesson_enrollment')],
            },
        ),
    ]
