"""
Django settings for Drive project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from dotenv import load_dotenv
import cloudinary
import cloudinary.uploader
import cloudinary.api
import smtplib
import ssl
import certifi

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-fallback-key-change-this')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
APPEND_SLASH = True

# Testing flag
TESTING = 'test' in sys.argv


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'django_ratelimit',
    'django_filters',
    'django_extensions',
    'cloudinary',
    'cloudinary_storage',

    'DriveApp.apps.DriveAppConfig',
]

AUTHENTICATION_BACKENDS = [
    'DriveApp.backends.EmailBackend',   # ← your custom backend
    'django.contrib.auth.backends.ModelBackend',  # ← keep as fallback
]

# Cloudinary Configuration
cloudinary.config(
    cloud_name=os.getenv('CLOUDINARY_CLOUD_NAME', 'dsfgsdjgz'),
    api_key=os.getenv('CLOUDINARY_API_KEY', '551648374292981'),
    api_secret=os.getenv('CLOUDINARY_API_SECRET', 'KmgyWi_QVc4xmvNj4Fe9Pj1JDyU'),
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'
STATICFILES_STORAGE = 'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Debug Toolbar settings - Only in development
if DEBUG and not TESTING:
    INSTALLED_APPS.append('debug_toolbar')
    MIDDLEWARE.insert(0, 'debug_toolbar.middleware.DebugToolbarMiddleware')

    DEBUG_TOOLBAR_CONFIG = {
        'SHOW_TOOLBAR_CALLBACK': lambda request: True,
        'RESULTS_CACHE_SIZE': 100,
        'SHOW_COLLAPSED': True,
    }

    INTERNAL_IPS = ['127.0.0.1', 'localhost']


ROOT_URLCONF = 'Drive.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Drive.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'SaasDjango'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', '127.0.0.1'),  # force TCP, not socket
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'connect_timeout': 10,
            'charset': 'utf8mb4',
        },
        'CONN_MAX_AGE': 0,          # no persistent connections
        'CONN_HEALTH_CHECKS': True, # Django 4.1+ validates before reuse
    }
}


# CORS Settings
CORS_ALLOWED_ORIGINS = os.getenv(
    'CORS_ALLOWED_ORIGINS',
    'https://drive-oj.vercel.app,http://127.0.0.1:5173'  # string, not tuple
).split(',')

CORS_ALLOW_CREDENTIALS = True

# Frontend URL (used in reset link)
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://127.0.0.1:5173')

# Redis config (separate DB from Celery broker)
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')
REDIS_PORT = int(os.getenv('REDIS_PORT', '6379'))
REDIS_RESET_DB = 2   # DB 0 = Celery broker, DB 2 = reset tokens

# REST Framework Settings
REST_FRAMEWORK = {
    # Pagination
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  
        'rest_framework.authentication.SessionAuthentication',

    ],
    # Permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    
    # Throttling (Rate Limiting)
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        
        'anon': '100/minute',

        # General rates        
        'user': '200/minute',
        'register_student': '10/hour',
        'school_users': '100/hour',
        'stats': '60/hour',
        'school_list': '100/hour',
        'school_create': '10/hour',
        'student_progress': '100/hour',
        'student_progress_update': '50/hour',
        'student_performance_prediction': '30/hour',
        
        # Authentication
        'login': '5/minute',
        'register': '10/hour',
        'burst': '60/minute',
        'school': '200/hour',
        'ip_based': '500/hour',

        # Lessons
        'lesson_list': '300/hour',
        'lesson_create': '50/hour',
        'lesson_update': '100/hour',
        'mark_attendance': '100/hour',
        'complete_lesson': '50/hour',
        'lesson_stats': '60/minute',
        'lesson_feedback': '100/hour',

        # Attendance
        'attendance_list': '100/min',
        'attendance_create': '50/hour',
        'attendance_update': '60/hour',
        'attendance_bulk_create': '10/hour',
        'attendance_stats': '50/min',

        # Feedback
        'feedback_list': '200/hour',
        'feedback_create': '10/hour',
        'feedback_update': '20/hour',
        'feedback_lesson_view': '100/hour',
        'feedback_my_view': '50/hour',
        'feedback_instructor_view': '60/minute',

        # Vehicles
        'vehicle_list': '300/hour',
        'vehicle_create': '20/hour',
        'vehicle_update': '100/hour',
        'vehicle_picture_upload': '30/hour',
        'vehicle_picture_manage': '50/hour',
        'vehicle_maintenance': '50/hour',
        'vehicle_statistics': '60/minute',
        'vehicle_history': '100/hour',

        # Schedules
        'schedule_list': '400/hour',
        'schedule_create': '50/hour',
        'schedule_update': '100/hour',
        'schedule_conflict_check': '200/hour',
        'schedule_my_schedule': '100/hour',
        'schedule_availability': '150/hour',
        'schedule_cancel': '20/hour',
        'schedule_reschedule': '30/hour',

        # Achievements
        'achievement_list': '200/hour',
        'achievement_award': '30/hour',
        'achievement_bulk_award': '10/hour',
        'achievement_check_milestones': '50/hour',
        'achievement_leaderboard': '100/hour',
        'achievement_statistics': '60/minute',

        # Communication
        'communication_template_list': '100/hour',
        'communication_template_create': '20/hour',
        'communication_template_update': '10/hour',
        'communication_template_duplicate': '20/hour',
        'communication_template_preview': '50/hour',
        'communication_template_usage_stats': '60/minute',
        
        'automated_message_list': '100/hour',
        'automated_message_create': '20/hour',
        'automated_message_update': '20/hour',
        'automated_message_bulk_create': '20/hour',
        'automated_message_bulk_cancel': '20/hour',
        'automated_message_send_now': '20/hour',
        'automated_message_statistics': '20/hour',
        'automated_message_schedule': '20/hour',

        # Analytics
        'school_analytic_list': '100/hour',
        'school_analytic_create': '20/hour',
        'school_analytic_update': '30/hour',
        'school_analytic_dashboard': '60/hour',
        'school_analytic_daily': '10/hour',
        'school_analytic_bulk_generate': '5/hour',
        'school_analytic_comparison': '50/hour',
        'school_analytic_trends': '30/hour',
        'school_analytic_alerts': '20/hour',
        'school_analytic_predictions': '40/hour',
        'school_analytic_export': '30/hour',
        'school_analytic_summary': '15/hour',
        'school_analytic_system_health': '60/hour',

        # Dashboard
        'dashboard_overview': '60/min',
        'dashboard_detailed': '30/min',
        'dashboard_quick_stats': '100/min',
        'dashboard_notifications': '50/min',

        # Subscriptions
        'subscription_plan_list': '100/hour',
        'subscription_plan_create': '10/hour',
        'subscription_plan_update': '30/hour',
        'subscription_plan_statistics': '60/hour',
        
        'school_subscription_list': '100/hour',
        'school_subscription_create': '5/hour',
        'school_subscription_update': '20/hour',
        'school_subscription_action': '15/hour',
        'school_subscription_usage': '100/hour',

        # Documents
        'student_document_list': '100/hour',
        'student_document_create': '20/hour',
        'student_document_update': '30/hour',
        'student_document_bulk_upload': '5/hour',
        'student_document_download': '50/hour',
        'student_document_my_documents': '60/hour',
        'student_document_student_docs': '40/hour',
        'student_document_statistics': '30/hour',
    },
    
    # Filtering
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    
    # Error handling
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler',
    
    # Renderer classes
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = os.getenv('TIME_ZONE', 'UTC')
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'DriveApp.User'


# ===== CELERY CONFIGURATION =====
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_RESULT_EXPIRES = 3600
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_SEND_SENT_EVENT = True
CELERY_WORKER_SEND_TASK_EVENTS = True


# ===== EMAIL CONFIGURATION =====
os.environ['SSL_CERT_FILE'] = certifi.where()
os.environ['REQUESTS_CA_BUNDLE'] = certifi.where()

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'   # True
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'  # False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)


# Override SSL context to use certifi certificates

ssl_context = ssl.create_default_context(cafile=certifi.where())



# Monkey-patch ssl to use certifi
_original_create_default_context = ssl.create_default_context
def _certifi_create_default_context(*args, **kwargs):
    kwargs.setdefault('cafile', certifi.where())
    return _original_create_default_context(*args, **kwargs)
ssl.create_default_context = _certifi_create_default_context
# ===== CACHE CONFIGURATION =====
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/1'),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_KWARGS': {
                'max_connections': 50,
                'retry_on_timeout': True,
            },
            'SOCKET_CONNECT_TIMEOUT': 5,
            'SOCKET_TIMEOUT': 5,
            'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'driving_school',
        'TIMEOUT': 300,
    }
}

# Rate limiting configuration
RATELIMIT_ENABLE = os.getenv('RATELIMIT_ENABLE', 'True') == 'True'
RATELIMIT_USE_CACHE = 'default'


# ===== LOGGING CONFIGURATION =====
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'cache_file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'cache.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 3,
            'formatter': 'simple',
        },
    },
    
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'WARNING' if not DEBUG else 'DEBUG',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django_ratelimit': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.core.cache': {
            'handlers': ['console', 'cache_file'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
    },
    
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}


# ===== SECURITY SETTINGS =====
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'


# ===== CACHE TIMEOUTS =====
CACHE_TIMEOUTS = {
    # User-related caches
    'user_queryset': 60 * 5,
    'user_stats': 60 * 10,
    'school_users': 60 * 3,
    
    # School-related caches
    'schools_queryset': 60 * 5,
    'school_data': 60 * 30,
    'school_student_count': 60 * 5,
    
    # Student profile caches
    'student_profile': 60 * 5,
    'student_progress': 60 * 2,
    'student_prediction': 60 * 10,
    'my_profile': 60 * 3,

    # Lesson-related caches
    'lessons_queryset': 60 * 3,
    'lesson_detail': 60 * 5,
    'lesson_attendance': 60 * 2,
    'lesson_feedback': 60 * 3,
    'lesson_schedule': 60 * 5,
    'upcoming_lessons': 60 * 2,
    'my_lessons': 60 * 3,
    'lesson_statistics': 60 * 5,

    # Attendance caches
    'attendance_queryset': 60 * 3,
    'attendance_detail': 60 * 5,
    'my_attendance': 60 * 2,
    'lesson_attendance_summary': 60 * 3,
    'student_attendance_summary': 60 * 3,
    'attendance_statistics': 60 * 5,
    'attendance_bulk_operations': 60 * 10,
    'attendance_filters': 60 * 2,

    # Feedback-related caches
    'feedback_queryset': 60 * 5,
    'feedback_detail': 60 * 5,
    'lesson_feedback': 60 * 5,
    'my_feedback': 60 * 3,
    'instructor_feedback': 60 * 5,
    'lesson_feedback_stats': 60 * 5,
    'instructor_feedback_stats': 60 * 5,
    
    # Vehicle-related caches
    'vehicles_queryset': 60 * 5,
    'vehicle_detail': 60 * 5,
    'vehicle_pictures': 60 * 5,
    'vehicles_available': 60 * 3,
    'vehicles_maintenance_due': 60 * 10,
    'vehicle_statistics': 60 * 10,
    'vehicle_history': 60 * 5,
    'my_school_vehicles': 60 * 3,

    # Schedule-related caches
    'schedules_queryset': 60 * 3,
    'my_schedule': 60 * 2,
    'upcoming_schedules': 60 * 3,
    'instructor_availability': 60 * 5,
    'vehicle_availability': 60 * 5,
    'my_schedule_mobile': 60 * 2,

    # Achievement-related caches
    'achievements_queryset': 60 * 5,
    'my_achievements': 60 * 3,
    'leaderboard': 60 * 5,
    'achievement_stats': 60 * 10,
    'student_progress': 60 * 5,
    'badges': 60 * 10,

    # Communication-related caches
    'communication_templates_queryset': 60 * 5,
    'communication_template_detail': 60 * 10,
    'templates_by_type': 60 * 5,
    'template_usage_stats': 60 * 10,
    'my_school_templates': 60 * 3,
    'available_variables': 60 * 60,
    'template_variables': 60 * 30,
    
    # Message-related caches
    'automated_messages_queryset': 60 * 2,
    'automated_message_detail': 60 * 5,
    'message_statistics': 60 * 10,
    'scheduled_messages': 60 * 1,
    'sent_messages': 60 * 5,
    'message_history': 60 * 10,
    'template_preview': 60 * 2,
    'communication_analytics': 60 * 15,
    'message_delivery_stats': 60 * 10,
    'template_effectiveness': 60 * 30,
    'bulk_message_operations': 60 * 5,
    'student_messages': 60 * 3,
    'my_messages': 60 * 2,
    'unread_messages_count': 60 * 1,

    # Analytics
    'analytics_queryset': 60 * 5,
    'analytics_dashboard': 60 * 5,
    'analytics_trends': 60 * 10,
    'analytics_comparison': 60 * 15,
    'analytics_alerts': 60 * 5,
    'analytics_predictions': 60 * 30,
    'analytics_summary': 60 * 5,
    'analytics_system_health': 60 * 2,
    
    # Reports
    'report_weekly': 60 * 120,
    'report_monthly': 60 * 360,
    'report_instructor_performance': 60 * 60,
    'report_student_progress': 60 * 30,
    'report_financial_summary': 60 * 120,
    'report_export': 60 * 60,

    # Student Documents
    'student_document_queryset': 60 * 5,
    'student_document_detail': 60 * 10,
    'my_documents': 60 * 5,
    'student_documents_view': 60 * 5,
    'document_download': 60 * 10,
    'document_statistics': 60 * 15,

    # Default
    'default': 60 * 5,
}